### ISSUE TITLE
Update to Python 3.6.x

### ISSUE THREAD

**Issue by awilliamson** [pet1330/teaching#10]
App is still using outdated 2.7.x Python syntax. This should be updated, as Python 2.7 is being phased out, and won't be supported for much longer.

**Comment by pet1330** [comment]
:thumbsdown:

**Comment by pet1330** [comment]
Still has 3 years worth of [support](https://hg.python.org/peps/rev/76d43e52d978)

**Comment by awilliamson** [comment]
Yes, however, the current changes needed to bring it inline with Python 3.6 are minimal. They can be done using '2to3' with 3-4 changes. This has already been done, and I'm currently running a Python 3.7 build perfectly fine. It makes sense to change now with minimal rewriting, and have future-proofing; especially as libraries will be going 3.6.x, and newer features will be left out of the 2.7 builds.

Using the __future__ module makes no sense when we're not that heavily invested in Python 2.7. It is literally a case of turning print from a keyword, into a function in a few areas. If we're building a system designed to outlast us for student use, it should be as robust and future-proof as we can currently make it.

**Comment by pet1330** [comment]
I would argue that [9% of the marker](https://w3techs.com/technologies/details/pl-python/all/all) is not future proof in any way, shape or form. I also think 3 years support is long enough for this to not be considered, as this is longer than most applications LTS support anyway. However, making it compatible with both versions, is something to be considered, but by default, I would leave it running on 2.7.
